# Generated by Django 2.2.6 on 2020-02-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='9e616a836c6545f8a6fca7c731e6cd50e3cf3d399d9b46968d63f644fb8055df', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='2bf54d191e174fc98d5f6706ef210cee28ebf169902f42f1be55f3ec5c40fca8', max_length=300, null=True),
        ),
    ]
